version: '3.5'
services:
  readme.uploader.mongo:
    image: mongo
    restart: always
    container_name: readme.uploader.mongo

    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_NAME}

    ports:
      - '${MONGO_PORT}:27017'

    volumes:
      - readme.mongo.uploader:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh ${MONGO_HOST}:${MONGO_PORT}/{MONGO_NAME} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.users.mongo.ui:
    image: mongo-express
    restart: always
    container_name: readme.uploader.mongo.ui
    ports:
      - '8083:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@readme.uploader.mongo:27017/

volumes:
  readme.mongo.uploader:
